### ISSUE TITLE
What is X,S1,S2,label in dataset.py?

### ISSUE THREAD

**Issue by garboa** [kentsommer/pytorch-value-iteration-networks#10]
Hello,I am a fresh learner of RL, so I am confused about how to  form the input.What is X,S1,S2,label?

**Comment by codenie** [comment]
X is the map and the destination, S1 and S2 are the position that start from. label is the right action

**Comment by QiXuanWang** [comment]
Why two positions:  S1 and S2, shouldn't it be one position to start from?  @codenie

**Comment by QiXuanWang** [comment]
Oh. guess it's x,y.

**Comment by kentsommer** [comment]
Correct it is x,y.
