### ISSUE TITLE
RUN ERROR

### ISSUE THREAD

**Issue by N-Kingsley** [kentsommer/pytorch-value-iteration-networks#7]
when I run 'python train.py --datafile dataset/gridworld_8x8.npz --imsize 8 --lr 0.005 --epochs 30 --k 10 --batch_size 128', it's ok,but again 'python train.py --datafile dataset/gridworld_16x16.npz --imsize 16 --lr 0.002 --epochs 30 --k 20 --batch_size 128' was run, an error occurred as follows:
ni@ubuntu:~/pytorch-value-iteration-networks$ python train.py --datafile dataset/gridworld_16x16.npz --imsize 16 --lr 0.002 --epochs 10 --k 20 --batch_size 128
Traceback (most recent call last):
  File "train.py", line 135, in <module>
    config.datafile, imsize=config.imsize, train=True, transform=transform)
  File "/home/ni/pytorch-value-iteration-networks/dataset/dataset.py", line 22, in __init__
    self._process(file, self.train)
  File "/home/ni/pytorch-value-iteration-networks/dataset/dataset.py", line 58, in _process
    images = images.astype(np.float32)
MemoryError

**Comment by michaalbert** [comment]
I get the same traceback when trying to train on the 28x28 domain. If the computer I am running it on didn't have 32GB RAM I'd blame it on not having enough RAM, but that seems very unlikely. Any idea where to even start debugging would be much appreciated.

**Comment by chachabules** [comment]
the memory error problem means that your computer don't have enough memory for this program because numpy need much memory to store the arrays. It is  to add some memory for virtual memory for your linux system or windows.  Your can also reduce the sample number. Hope to help you.

**Comment by kentsommer** [comment]
Closing out as there are no new comments for a while and I agree that this is likely an issue of simply running out of memory.
